### PR TITLE
chore: update dir-index-html to v1.2.0

### PR DESCRIPTION
**Pull request by WhiteEgg**
Update dir-index-html to v1.2.0
Update upstream url
https://github.com/TRON-US/dir-index-html/pull/4

### CODE REVIEW

**Comment by taiyangc** [comment]
ok to test

**Comment by taiyangc** [comment]
@WhiteEgg One of the tests failed, please try to run `make test` locally.

**Comment by WhiteEgg** [comment]
@taiyangc https://github.com/ipfs/dir-index-html/issues/42 looks upstream issue
fix in https://github.com/ipfs/go-ipfs/pull/7699 and https://github.com/ipfs/dir-index-html/pull/43
merge patch or skip test?

**Comment by taiyangc** [comment]
@WhiteEgg ok to apply patch as long as it's not bringing other module upgrades?

**Comment by WhiteEgg** [comment]
Yeah, only upgrade dir-index-html and go-btfs, but may some other issues

**Comment by taiyangc** [comment]
Hmm maybe it's a test more complicated to modify than just name changes...

**Comment by WhiteEgg** [comment]
But... https://github.com/ipfs/go-ipfs/commit/2feff332354b376a211c956902e0ad64de61fa0c i think it just want to show `Index of /` not `Index of /btfs/$Qmhash` ? try to find more issues

**Comment by laipogo** [comment]
Thank you, @WhiteEgg .

**Pull request closed without merging**
