### PR TITLE
BTFS-1573: enabled the tests failed. 

### PR DESCRIPTION
**Pull request by steveyeom**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior?** (You can also refer to a JIRA ticket here)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **What dependencies / modules need to be updated as pre-requisites?** (Include relevant PR links here)

* **Description of changes**

---

* **Please check if the PR fulfills these requirements**
- [ ] The subject of this PR contains a JIRA ticket BTFS-xxxx (N/A for community PRs)
- [ ] PR description and commit messages are [good and meaningful](https://chris.beams.io/posts/git-commit/)
- [ ] Unit tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **Please make sure the following procedures have been applied before requesting reviewers**
- [ ] Code changes closely follow [Go Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments)
- [ ] Code has been *rebased* against latest master (`git merge` not recommended, unless you know what you are doing)
- [ ] Code changes have run through `go fmt`
- [ ] Code changes have run through `go mod tidy`
- [ ] All unit tests passed locally (`make test_go_test`)

### CODE REVIEW

**Comment by richlee33** [comment]
it passed once and failed once.  i am triggering it 1 more time.

**Comment by taiyangc** [comment]
@richlee33 does not convince me we fixed everything... is longer timeout is the only thing here?

**Comment by richlee33** [comment]
correct.  and the coreunix/test test did not need the longer timeout because its finishing within 5 seconds now.

**Comment by taiyangc** [comment]
I don't see how we can prove the tests are "fixed". It seems to me it's not showing error because builds are more stable/reliable. But, doesn't hurt to turn them on again.

**Comment by steveyeom** [comment]
frankly speaking, i think there is a chance we hit the same error but simply it is not showing consistently.. but the issue may be in a deeper layer.. We should have fixed when the error is occuring consistently

**Comment by steveyeom** [comment]
Closing this PR since I got into the original issue with the AWS linux.

**Pull request closed without merging**
