### PR TITLE
Fix golang 1.13 compilation issues (on master)

### PR DESCRIPTION
**Pull request by taiyangc**
cherry-pick from #154

### CODE REVIEW

**Comment by richlee33** [comment]
hi @taiyangc  i am getting the following error in the launchpad package when i am trying to run `go mod download`

`richards-MacBook-Pro:go-btfs richardlee$ go mod download
go: finding github.com/mhutchinson/golangci-lint v1.17.2-0.20190819125825-d18f2136e32b
go: github.com/mhutchinson/golangci-lint@v1.17.2-0.20190819125825-d18f2136e32b: unknown revision d18f2136e32b
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in /Users/richardlee/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
go: error loading module requirements`

**Comment by taiyangc** [comment]
@richlee33 could you retry the latest commit?

**Comment by richlee33** [comment]
i was able to run the unit tests.  however the `make install` fails. i installed the brz package to try and work around the issue but then i get the error below since i dont have python 2.6 on my mac.  

`go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in /Users/richardlee/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exit status 1:
	bzr: ERROR: Couldn't import bzrlib and dependencies.
	Please check the directory containing bzrlib is on your PYTHONPATH.

	Traceback (most recent call last):
	  File "/usr/local/bin/bzr", line 74, in <module>
	    import bzrlib
	ImportError: No module named bzrlib
go: error loading module requirements
make: *** [cmd/btfs-install] Error 1`

**Comment by richlee33** [comment]
@jin-tron @hzmbeyond80 @taiyangc  I think the team needs to decide and then scope out the work to upgrade to golang 1.3 and if we want to let go of that shared requirement that came from go-ipfs.  i am new to golang and dont know how big of a deal changing the version of the compiler will be.

**Comment by taiyangc** [comment]
@richlee33 It's not the shared requirement that prevented the upgrade. IPFS itself upgraded fine.

The culprit was go-bip32 which was added by a go-btfs feature

```
$ go mod why launchpad.net/gocheck
# launchpad.net/gocheck
github.com/TRON-US/go-btfs/cmd/btfs
github.com/tyler-smith/go-bip32
github.com/FactomProject/basen
github.com/FactomProject/basen.test
launchpad.net/gocheck
```

go-bip32 is not actively maintained so I am not surprised it suffers from this problem. But if upgrading to 1.13 altogether fixes this issue, it's not a bad thing to do (staying up-to-date).

**Comment by richlee33** [comment]
i am trying to wrap my head around why upgrading to go v1.3 caused a new package dependency that was not there prior.  the go-bip32 module was added to go-btfs/init.go about a month ago.

**Comment by taiyangc** [comment]
OK, here is the drill down:

Firstly, `go mod tidy` requires all test-related dependencies to also be indirect dependencies ([ref](https://github.com/golang/go/issues/29790#issuecomment-456480271)). Prior to 1.13, this problem was unnoticed (so not having the dependency was _actually buggy_), but got fixed [here](https://github.com/golang/go/issues/27063). So as soon as I upgrade to 1.13, this indirect dependency is _correctly_ added. As you can see here: https://github.com/tyler-smith/go-bip32/blob/master/vendor/github.com/FactomProject/basen/basen_test.go uses `"launchpad.net/gocheck"`.

Now, the reason for this `exec: "bzr": executable file not found in $PATH` is because go is trying to check out a repo `"launchpad.net/gocheck"` that uses bazaar, instead of git, and you need the software in order to correctly do this. This was cleared explained [here](https://www.reddit.com/r/golang/comments/arwh76/error_while_dowloading_packages_using_go_modules/).

And the final reason of why having stayed on 1.12 will see this failure, while on my machine (1.13) does not, is due to this change: `The GOPROXY environment variable may now be set to a comma-separated list of proxy URLs or the special token direct, and its default value is now https://proxy.golang.org,direct.` So Go 1.13 now uses a Google-backed mirror for faster, cached downloads without needing to checking out the original source/installing these esoteric VCS such as Bazaar (bzr).

Having explained above, the real issue is go-bip32 using a module using another module that should be updated to use [gopkg.in/check.v1](https://github.com/go-check/check) instead of the old, deprecated launchpad.net/gocheck.

For now, upgrading to 1.13 altogether is the safest choice.

**Comment by richlee33** [comment]
thanks @taiyangc for spelling this out.  i uninstalled golang 1.12 and installed 1.13 and the unit tests work fine.  also the `make install` worked fine. i had to update the Dockerfile.unit_test to use a different base image.  i will make separate stories to update the README and the Dockerfiles.

**Pull request merged**
